### ISSUE TITLE
TypeError: config.guilds is not iterable

### ISSUE THREAD

**Issue by WillWillCode** [Khaaz/Cross-Server-Bot#11]
Try for the life of me I cannot figure out where this is error is. Could you possible write more detailed docs for the bot or open a support server for it? Also, I'd appreciate if you'd help me resolve this.

Love the bot and can't wait for a v2!
![image](https://user-images.githubusercontent.com/34786399/88999488-43cb6100-d2e4-11ea-9c58-cf7dd0174820.png)

**Comment by bsian03** [comment]
Sounds like something wrong with the config - screenshot/contents of it would be good

**Comment by Khaaz** [comment]
For the record we're on v3, and this is the stable version. We don't have anything planned on this right now.
I have bots running in production running this so it should work without issue. It's most likely a configuration problem as Bsian already pointed out. We will be able to help if you give us more info about your configuration. Support server [here](https://discord.gg/QZ6B5US).

There are however probably room for improvement about the documentation, I'd be happy to accept PR improving the readme or even constructive feedback if there are some particular point that looked very obscure to you.

**Comment by bsian03** [comment]
OP is on v3 as mentioned on Discord (also in the screenshot) and this is confirmed a bug by me, see the following PR

**Comment by bsian03** [comment]
Issue is actually from the README, see [original message](https://canary.discordapp.com/channels/365236789855649814/691324975248048128/739914868785938566)
