### ISSUE TITLE
None of the commands are working and no way to delte

### ISSUE THREAD

**Issue by JSai23** [Khaaz/Cross-Server-Bot#17]
I put the role for my moderators under the config file for that server but not even I can run the commands and lock. Also deleting a message in one server does not delete it in the others.

**Comment by bsian03** [comment]
Deleting messages see #16

**Comment by bsian03** [comment]
Also relaying your config file here would be good. Please remove your bot token when you do this

**Comment by Khaaz** [comment]
`managerRoles` takes the roles ID and not the roles name. Not sure what you have in your config right now

**Comment by JSai23** [comment]
Solved by fixing config
